// lyrics.js: written by bin/song-sync from lyrics-video timings. Cue times for acting a line
// and cutting on it; the kit's no-text rule still applies.
const LYRICS = [
  {"text": "Now the stock have started dying for the Lord has sent a drought", "start": 11.95, "end": 16.27},
  {"text": "But we're sick of prayers and providence, we're going to do without", "start": 16.27, "end": 20.49},
  {"text": "With the derricks up above us and the solid earth below", "start": 20.49, "end": 25.65},
  {"text": "We are waiting at the lever for the word to let her go", "start": 25.65, "end": 29.93},
  {"text": "Oh we'll get artesian water deeper down.", "start": 29.93, "end": 33.57},
  {"text": "Sinking down, deeper down,", "start": 33.57, "end": 37.21},
  {"text": "Oh we'll sink it deeper down", "start": 37.21, "end": 39.29},
  {"text": "Sinking down, deeper down,", "start": 39.29, "end": 42.2},
  {"text": "Oh we'll sink it deeper down", "start": 42.2, "end": 51.3},
  {"text": "The drill is plugging downward at a thousand feet of level,", "start": 51.3, "end": 55.57},
  {"text": "If the Lord won't send us water, oh, we'll get it from the devil;", "start": 55.57, "end": 59.91},
  {"text": "It's time they heard us knocking on the roof of Satan's dwelling", "start": 59.91, "end": 65.13},
  {"text": "We'll get artesian water if we cave the roof of hell in", "start": 65.13, "end": 69.37},
  {"text": "Yes, we'll get it from the devil deeper down.", "start": 69.37, "end": 73.4},
  {"text": "Sinking down, deeper down,", "start": 73.4, "end": 76.05},
  {"text": "Oh we'll sink it deeper down", "start": 76.05, "end": 79.0},
  {"text": "Sinking down, deeper down,", "start": 79.0, "end": 81.9},
  {"text": "Oh we'll sink it deeper down", "start": 81.9, "end": 85.83},
  {"text": "Now, our engine's built in Glasgow by a very canny Scot,", "start": 85.83, "end": 90.55},
  {"text": "And he marked it twenty horse-power, but he didn't know what's what.", "start": 90.55, "end": 95.11},
  {"text": "When Canadian Bill is firing with the sun-dried gidgee logs,", "start": 95.11, "end": 100.05},
  {"text": "She can equal thirty horses and a score or so of dogs.", "start": 100.05, "end": 104.29},
  {"text": "So we're bound to get the water deeper down", "start": 104.29, "end": 108.67},
  {"text": "Sinking down, deeper down,", "start": 108.67, "end": 111.07},
  {"text": "Oh we'll sink it deeper down", "start": 111.07, "end": 113.47},
  {"text": "Sinking down, deeper down,", "start": 113.47, "end": 115.87},
  {"text": "Oh we'll sink it deeper down", "start": 115.87, "end": 118.73},
  {"text": "But the shaft has started caving and the sinking's very slow,", "start": 118.73, "end": 125.41},
  {"text": "And the yellow rods are bending in the water down below,", "start": 125.41, "end": 129.57},
  {"text": "And the tubes are always jamming, and they can't be made to shift", "start": 129.57, "end": 134.99},
  {"text": "Till we nearly burst the engine with a forty horse-power lift,", "start": 134.99, "end": 139.23},
  {"text": "While the stubborn drill is ramming deeper down.", "start": 139.23, "end": 143.05},
  {"text": "Sinking down, deeper down,", "start": 143.05, "end": 146.31},
  {"text": "Oh we'll sink it deeper down", "start": 146.31, "end": 148.43},
  {"text": "Sinking down, deeper down,", "start": 148.43, "end": 151.18},
  {"text": "Oh we'll sink it deeper down", "start": 151.18, "end": 153.79},
  {"text": "If we fail to get the water, then it's ruin to the squatter,", "start": 153.79, "end": 160.51},
  {"text": "For the drought is on the station and the weather's growing hotter,", "start": 160.51, "end": 164.59},
  {"text": "But there's no artesian water though we've passed three thousand feet", "start": 164.59, "end": 169.79},
  {"text": "And the contract price is growing and the boss is nearly beat", "start": 169.79, "end": 173.93},
  {"text": "But we're bound to get the water deeper down", "start": 173.93, "end": 177.67},
  {"text": "Sinking down, deeper down,", "start": 177.67, "end": 180.89},
  {"text": "Oh we'll sink it deeper down", "start": 180.89, "end": 183.05},
  {"text": "Sinking down, deeper down,", "start": 183.05, "end": 186.15},
  {"text": "Oh we'll sink it deeper down", "start": 186.15, "end": 188.97},
  {"text": "But it must be down beneath us, so it's down we've got to go", "start": 188.97, "end": 195.05},
  {"text": "Though she's bumping on the solid rock four thousand feet below", "start": 195.05, "end": 199.19},
  {"text": "So we'll hammer, splice, and bully every snapping rod and bend,", "start": 199.19, "end": 204.61},
  {"text": "We'll patch her up with fencing-wire and drive her to the end,", "start": 204.61, "end": 208.86},
  {"text": "For we'll wring it from the bedrock, deeper down.", "start": 208.86, "end": 212.41},
  {"text": "Sinking down, deeper down,", "start": 212.41, "end": 215.65},
  {"text": "Oh we'll sink it deeper down", "start": 215.65, "end": 218.51},
  {"text": "Sinking down, deeper down,", "start": 218.51, "end": 220.73},
  {"text": "Oh we'll sink it deeper down", "start": 220.73, "end": 222.73},
  {"text": "Hark! the whistle's blowing with a wild, exultant blast,", "start": 222.73, "end": 229.85},
  {"text": "And the boys are madly cheering, for they've struck the flow at last;", "start": 229.85, "end": 234.17},
  {"text": "It's rushing up the tubing from four thousand feet below,", "start": 234.17, "end": 238.45},
  {"text": "Till it spouts above the casing in a million-gallon flow.", "start": 238.45, "end": 243.61},
  {"text": "It's flowing, ever flowing, deeper down.", "start": 243.61, "end": 247.61},
  {"text": "Sinking down, deeper down,", "start": 247.61, "end": 250.31},
  {"text": "Oh we'll sink it deeper down", "start": 250.31, "end": 252.55},
  {"text": "Sinking down, deeper down,", "start": 252.55, "end": 255.61},
  {"text": "Oh we'll sink it deeper down", "start": 255.61, "end": 259.9},
  {"text": "And it's clear away the timber and it's let the water run,", "start": 259.9, "end": 263.05},
  {"text": "How it glimmers in the shadow, how it flashes in the sun!", "start": 263.05, "end": 269.05},
  {"text": "By the silent belts of timber, by the miles of blazing plain", "start": 269.05, "end": 272.1},
  {"text": "It is bringing hope and comfort to the thirsty land again.", "start": 272.1, "end": 277.19},
  {"text": "It is flowing, ever flowing, further down.", "start": 277.19, "end": 281.1},
  {"text": "Sinking down, deeper down,", "start": 281.1, "end": 284.28},
  {"text": "Oh we'll sink it deeper down", "start": 284.28, "end": 286.52},
  {"text": "Sinking down, deeper down,", "start": 286.52, "end": 289.6},
  {"text": "Oh we'll sink it deeper down", "start": 289.6, "end": 292.1},
  {"text": "Sinking down, deeper down,", "start": 292.1, "end": 301.16},
  {"text": "Oh we'll sink it deeper down", "start": 302.0, "end": 302.0}
];
