// lyrics.js: written by bin/song-sync from lyrics-video timings. Cue times for acting a line
// and cutting on it; the kit's no-text rule still applies.
const LYRICS = [
  {"text": "Now the stock have started dying for the Lord has sent a drought", "start": 7.4, "end": 12.22},
  {"text": "But we're sick of prayers and providence, we're going to do without", "start": 12.22, "end": 16.46},
  {"text": "With the derricks up above us and the solid earth below", "start": 16.46, "end": 21.78},
  {"text": "We are waiting at the lever for the word to let her go", "start": 21.78, "end": 26.3},
  {"text": "Oh we'll get artesian water deeper down.", "start": 26.3, "end": 29.54},
  {"text": "Sinking down, deeper down,", "start": 29.54, "end": 33.44},
  {"text": "Oh we'll sink it deeper down", "start": 33.44, "end": 35.63},
  {"text": "Sinking down, deeper down,", "start": 35.63, "end": 38.55},
  {"text": "Oh we'll sink it deeper down", "start": 38.55, "end": 47.9},
  {"text": "The drill is plugging downward at a thousand feet of level,", "start": 47.9, "end": 52.16},
  {"text": "If the Lord won't send us water, oh, we'll get it from the devil;", "start": 52.16, "end": 56.52},
  {"text": "It's time they heard us knocking on the roof of Satan's dwelling", "start": 56.52, "end": 61.94},
  {"text": "We'll get artesian water if we cave the roof of hell in", "start": 61.94, "end": 66.08},
  {"text": "Yes, we'll get it from the devil deeper down.", "start": 66.08, "end": 69.7},
  {"text": "Sinking down, deeper down,", "start": 69.7, "end": 72.7},
  {"text": "Oh we'll sink it deeper down", "start": 72.7, "end": 75.6},
  {"text": "Sinking down, deeper down,", "start": 75.6, "end": 78.4},
  {"text": "Oh we'll sink it deeper down", "start": 78.4, "end": 81.24},
  {"text": "Now, our engine's built in Glasgow by a very canny Scot,", "start": 81.24, "end": 87.68},
  {"text": "And he marked it twenty horse-power, but he didn't know what's what.", "start": 87.68, "end": 92.04},
  {"text": "When Canadian Bill is firing with the sun-dried gidgee logs,", "start": 92.04, "end": 97.46},
  {"text": "She can equal thirty horses and a score or so of dogs.", "start": 97.46, "end": 101.6},
  {"text": "So we're bound to get the water deeper down", "start": 101.6, "end": 105.01},
  {"text": "Sinking down, deeper down,", "start": 105.01, "end": 107.89},
  {"text": "Oh we'll sink it deeper down", "start": 107.89, "end": 110.87},
  {"text": "Sinking down, deeper down,", "start": 110.87, "end": 114.3},
  {"text": "Oh we'll sink it deeper down", "start": 114.3, "end": 116.3},
  {"text": "But the shaft has started caving and the sinking's very slow,", "start": 116.3, "end": 122.92},
  {"text": "And the yellow rods are bending in the water down below,", "start": 122.92, "end": 127.18},
  {"text": "And the tubes are always jamming, and they can't be made to shift", "start": 127.18, "end": 132.68},
  {"text": "Till we nearly burst the engine with a forty horse-power lift,", "start": 132.68, "end": 136.94},
  {"text": "While the stubborn drill is ramming deeper down.", "start": 136.94, "end": 140.47},
  {"text": "Sinking down, deeper down,", "start": 140.47, "end": 143.29},
  {"text": "Oh we'll sink it deeper down", "start": 143.29, "end": 146.2},
  {"text": "Sinking down, deeper down,", "start": 146.2, "end": 149.02},
  {"text": "Oh we'll sink it deeper down", "start": 149.02, "end": 151.94},
  {"text": "If we fail to get the water, then it's ruin to the squatter,", "start": 151.94, "end": 158.38},
  {"text": "For the drought is on the station and the weather's growing hotter,", "start": 158.38, "end": 162.74},
  {"text": "But there's no artesian water though we've passed three thousand feet", "start": 162.74, "end": 167.98},
  {"text": "And the contract price is growing and the boss is nearly beat", "start": 167.98, "end": 172.18},
  {"text": "But we're bound to get the water deeper down", "start": 172.18, "end": 175.96},
  {"text": "Sinking down, deeper down,", "start": 175.96, "end": 178.72},
  {"text": "Oh we'll sink it deeper down", "start": 178.72, "end": 181.5},
  {"text": "Sinking down, deeper down,", "start": 181.5, "end": 184.16},
  {"text": "Oh we'll sink it deeper down", "start": 184.16, "end": 189.2},
  {"text": "But it must be down beneath us, so it's down we've got to go", "start": 189.2, "end": 193.6},
  {"text": "Though she's bumping on the solid rock four thousand feet below", "start": 193.6, "end": 197.9},
  {"text": "So we'll hammer, splice, and bully every snapping rod and bend,", "start": 197.9, "end": 203.42},
  {"text": "We'll patch her up with fencing-wire and drive her to the end,", "start": 203.42, "end": 207.68},
  {"text": "For we'll wring it from the bedrock, deeper down.", "start": 207.68, "end": 211.23},
  {"text": "Sinking down, deeper down,", "start": 211.23, "end": 214.05},
  {"text": "Oh we'll sink it deeper down", "start": 214.05, "end": 216.98},
  {"text": "Sinking down, deeper down,", "start": 216.98, "end": 220.16},
  {"text": "Oh we'll sink it deeper down", "start": 220.16, "end": 225.55},
  {"text": "Hark! the whistle's blowing with a wild, exultant blast,", "start": 225.55, "end": 229.24},
  {"text": "And the boys are madly cheering, for they've struck the flow at last;", "start": 229.24, "end": 233.54},
  {"text": "It's rushing up the tubing from four thousand feet below,", "start": 233.54, "end": 238.58},
  {"text": "Till it spouts above the casing in a million-gallon flow.", "start": 238.58, "end": 243.0},
  {"text": "It's flowing, ever flowing, deeper down.", "start": 243.0, "end": 246.86},
  {"text": "Sinking down, deeper down,", "start": 246.86, "end": 249.5},
  {"text": "Oh we'll sink it deeper down", "start": 249.5, "end": 252.2},
  {"text": "Sinking down, deeper down,", "start": 252.2, "end": 254.88},
  {"text": "Oh we'll sink it deeper down", "start": 254.88, "end": 257.68},
  {"text": "And it's clear away the timber and it's let the water run,", "start": 257.68, "end": 262.26},
  {"text": "How it glimmers in the shadow, how it flashes in the sun!", "start": 262.26, "end": 266.58},
  {"text": "By the silent belts of timber, by the miles of blazing plain", "start": 266.58, "end": 270.88},
  {"text": "It is bringing hope and comfort to the thirsty land again.", "start": 270.88, "end": 275.08},
  {"text": "It is flowing, ever flowing, further down.", "start": 275.08, "end": 278.79},
  {"text": "Sinking down, deeper down,", "start": 278.79, "end": 281.67},
  {"text": "Oh we'll sink it deeper down", "start": 281.67, "end": 284.62},
  {"text": "Sinking down, deeper down,", "start": 284.62, "end": 287.38},
  {"text": "Oh we'll sink it deeper down", "start": 287.38, "end": 290.2},
  {"text": "Sinking down, deeper down,", "start": 290.2, "end": 292.75},
  {"text": "Oh we'll sink it deeper down", "start": 292.75, "end": 292.8}
];
